package com.pharmacy;
// Generated 22-Mar-2020, 11:16:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="online_pharmacy"
)
public class Category  implements java.io.Serializable {


     private Integer cid;
     private String cname;
     private Set<Medicines> medicineses = new HashSet<Medicines>(0);

    public Category() {
    }

	
    public Category(String cname) {
        this.cname = cname;
    }
    public Category(String cname, Set<Medicines> medicineses) {
       this.cname = cname;
       this.medicineses = medicineses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cid", unique=true, nullable=false)
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    
    @Column(name="cname", nullable=false, length=20)
    public String getCname() {
        return this.cname;
    }
    
    public void setCname(String cname) {
        this.cname = cname;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<Medicines> getMedicineses() {
        return this.medicineses;
    }
    
    public void setMedicineses(Set<Medicines> medicineses) {
        this.medicineses = medicineses;
    }




}


