package com.pharmacy;
// Generated 22-Mar-2020, 11:16:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Medicines generated by hbm2java
 */
@Entity
@Table(name="medicines"
    ,catalog="online_pharmacy"
)
public class Medicines  implements java.io.Serializable {


     private Integer mid;
     private Category category;
     private String mname;
     private int mpower;
     private Date mandate;
     private Date expdate;
     private int stock;
     private float mcost;
     private String mdesc;
     private Set<Purchase> purchases = new HashSet<Purchase>(0);

    public Medicines() {
    }

	
    public Medicines(Category category, String mname, int mpower, Date mandate, Date expdate, int stock, float mcost) {
        this.category = category;
        this.mname = mname;
        this.mpower = mpower;
        this.mandate = mandate;
        this.expdate = expdate;
        this.stock = stock;
        this.mcost = mcost;
    }
    public Medicines(Category category, String mname, int mpower, Date mandate, Date expdate, int stock, float mcost, String mdesc, Set<Purchase> purchases) {
       this.category = category;
       this.mname = mname;
       this.mpower = mpower;
       this.mandate = mandate;
       this.expdate = expdate;
       this.stock = stock;
       this.mcost = mcost;
       this.mdesc = mdesc;
       this.purchases = purchases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="mid", unique=true, nullable=false)
    public Integer getMid() {
        return this.mid;
    }
    
    public void setMid(Integer mid) {
        this.mid = mid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mcategory", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="mname", nullable=false, length=30)
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }

    
    @Column(name="mpower", nullable=false)
    public int getMpower() {
        return this.mpower;
    }
    
    public void setMpower(int mpower) {
        this.mpower = mpower;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mandate", nullable=false, length=10)
    public Date getMandate() {
        return this.mandate;
    }
    
    public void setMandate(Date mandate) {
        this.mandate = mandate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="expdate", nullable=false, length=10)
    public Date getExpdate() {
        return this.expdate;
    }
    
    public void setExpdate(Date expdate) {
        this.expdate = expdate;
    }

    
    @Column(name="stock", nullable=false)
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }

    
    @Column(name="mcost", nullable=false, precision=12, scale=0)
    public float getMcost() {
        return this.mcost;
    }
    
    public void setMcost(float mcost) {
        this.mcost = mcost;
    }

    
    @Column(name="mdesc", length=100)
    public String getMdesc() {
        return this.mdesc;
    }
    
    public void setMdesc(String mdesc) {
        this.mdesc = mdesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicines")
    public Set<Purchase> getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Set<Purchase> purchases) {
        this.purchases = purchases;
    }




}


