package com.pharmacy;
// Generated 22-Mar-2020, 11:16:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Purchase generated by hbm2java
 */
@Entity
@Table(name="purchase"
    ,catalog="online_pharmacy"
)
public class Purchase  implements java.io.Serializable {


     private Integer purchaseId;
     private Medicines medicines;
     private Orders orders;
     private int quantity;
     private Date dop;

    public Purchase() {
    }

    public Purchase(Medicines medicines, Orders orders, int quantity, Date dop) {
       this.medicines = medicines;
       this.orders = orders;
       this.quantity = quantity;
       this.dop = dop;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="purchase_id", unique=true, nullable=false)
    public Integer getPurchaseId() {
        return this.purchaseId;
    }
    
    public void setPurchaseId(Integer purchaseId) {
        this.purchaseId = purchaseId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mid", nullable=false)
    public Medicines getMedicines() {
        return this.medicines;
    }
    
    public void setMedicines(Medicines medicines) {
        this.medicines = medicines;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false)
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dop", nullable=false, length=19)
    public Date getDop() {
        return this.dop;
    }
    
    public void setDop(Date dop) {
        this.dop = dop;
    }




}


