package com.pharmacy;
// Generated 22-Mar-2020, 11:16:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="online_pharmacy"
)
public class Users  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String username;
     private String password;
     private String phoneNum;
     private String address;
     private String email;
     private Date dateCreated;
     private Integer userLevel;
     private Set<Orders> orderses = new HashSet<Orders>(0);

    public Users() {
    }

	
    public Users(String name, String username, String password, String phoneNum, String address, String email, Date dateCreated) {
        this.name = name;
        this.username = username;
        this.password = password;
        this.phoneNum = phoneNum;
        this.address = address;
        this.email = email;
        this.dateCreated = dateCreated;
    }
    public Users(String name, String username, String password, String phoneNum, String address, String email, Date dateCreated, Integer userLevel, Set<Orders> orderses) {
       this.name = name;
       this.username = username;
       this.password = password;
       this.phoneNum = phoneNum;
       this.address = address;
       this.email = email;
       this.dateCreated = dateCreated;
       this.userLevel = userLevel;
       this.orderses = orderses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=25)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="username", nullable=false, length=25)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="phone_num", nullable=false, length=10)
    public String getPhoneNum() {
        return this.phoneNum;
    }
    
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }

    
    @Column(name="address", nullable=false, length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_created", nullable=false, length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    
    @Column(name="user_level")
    public Integer getUserLevel() {
        return this.userLevel;
    }
    
    public void setUserLevel(Integer userLevel) {
        this.userLevel = userLevel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }




}


